version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python /app/backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/backend
    env_file:
    - ./.env  
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=rlaskatlr"
      - "POSTGRES_DB=polls"
volumes:
  postgres_data: